# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EpifiAssignment' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EpifiAssignment

  pod 'Toast'
  pod 'AlamofireImage', '~> 3.5'

  target 'EpifiAssignmentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EpifiAssignmentUITests' do
    # Pods for testing
  end

end
